### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by ivptr** [WildPHP/irc-bot#170]
On Windows `composer install` shows:
```
Root composer.json requires PHP extension ext-posix * but it is missing from your system. Install or enable PHP's posix extension.
```

`composer install --ignore-platform-reqs` is a workaround for this issue. Don't know is there a better solution.

Probably documentation needs updating for this.

**Comment by Yoshi2889** [comment]
Looks like that's only really required for the root check in the wildphp.php entry point, not for the main code.

That entry point already checks whether the function exists. Therefore I think it's safe enough to drop the requirement from composer.json.

I'll take a better look and see if there's alternative methods to do this check. Maybe there's a package with a platform independent solution.

Do note that I don't really test the bot on Windows as it's not my primary development machine, plus PHP has quirks and other various things that don't work on Windows, I'm not sure if the bot uses anything that's impacted by this.
Although with the increase in test coverage it might be possible to at least deploy Scrutinizer to test on Windows, but I'll open a new issue for that.
