### ISSUE TITLE
Support self-signed certs

### ISSUE THREAD

**Issue by Luke081515** [WildPHP/irc-bot#90]
Currently if you are using a self-signed cert at your network, the bot will not connect:
`[2017-10-23 01:48:01] wildphp.ERROR: An error occurred in the IRC connection: {"message":"Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed","file":"/home/luke/PHPBot/vendor/react/socket/src/StreamEncryption.php","line":117} []
`
it would be nice if you can override that in your config, since if you know that the connection is secure (for example it is your server), then this kind of ssl connection is more secure than plaintext.

**Comment by Yoshi2889** [comment]
The reactphp/socket documentation makes note of how to allow insecure connections: https://github.com/reactphp/socket#connector (scroll down a little).

That makes this more of a documentation issue.

**Comment by Yoshi2889** [comment]
It's been 3 years since this was opened... oops. Linking #161 to this.
